replicaCount: 1

image:
  repository: comsci
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  port: 8000

prometheus:
  enabled: true

jaeger:
  enabled: true

grafana:
  enabled: true

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: comsci.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://jaeger-collector:4317"
  - name: LOG_LEVEL
    value: "INFO"
  - name: PROMETHEUS_PUSH_GATEWAY
    value: "http://prometheus-pushgateway:9091"
