apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "comsci.fullname" .}}
  labels: {{- include "comsci.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels: {{- include "comsci.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels: {{- include "comsci.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Chart.Name}}
          image: "localhost:5000/comsci:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # Add other container configurations as needed

---
apiVersion: v1
kind: Service
metadata:
  name: {{include "comsci.fullname" .}}
  labels: {{- include "comsci.labels" . | nindent 4}}
spec:
  selector: {{- include "comsci.selectorLabels" . | nindent 4}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 8000
