{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comsci.fullname" . }}-grafana
  labels:
    {{- include "comsci.labels" . | nindent 4 }}
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "comsci.selectorLabels" . | nindent 6 }}
      app: grafana
  template:
    metadata:
      labels:
        {{- include "comsci.selectorLabels" . | nindent 8 }}
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.2.2
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "http://comsci.local:30080/grafana"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comsci.fullname" . }}-grafana
  labels:
    {{- include "comsci.labels" . | nindent 4 }}
    app: grafana
spec:
  selector:
    {{- include "comsci.selectorLabels" . | nindent 4 }}
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
{{- end }}