{{- if .Values.jaeger.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comsci.fullname" . }}-jaeger
  labels:
    {{- include "comsci.labels" . | nindent 4 }}
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "comsci.selectorLabels" . | nindent 6 }}
      app: jaeger
  template:
    metadata:
      labels:
        {{- include "comsci.selectorLabels" . | nindent 8 }}
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.25
          ports:
            - containerPort: 16686
            - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comsci.fullname" . }}-jaeger
  labels:
    {{- include "comsci.labels" . | nindent 4 }}
    app: jaeger
spec:
  selector:
    {{- include "comsci.selectorLabels" . | nindent 4 }}
    app: jaeger
  ports:
    - port: 16686
      name: ui
    - port: 4317
      name: grpc
{{- end }}